workflows:
  build_ios_only:
    name: Build iOS Sempre Online
    environment:
      flutter: stable        # versão estável mais recente
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pub get
        script: flutter pub get

      - name: Build iOS release (sem assinatura)
        script: flutter build ios --release --no-codesign

    artifacts:
      # Resultado do build — útil para subir no Xcode Organizer ou empacotar .ipa depois
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - noc@semppreonline.com.br
