workflows:
  build_ios_only:
    name: Build iOS Sempre Online
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pub get
        script: flutter pub get

      - name: Build release (sem assinatura)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - noc@semppreonline.com.br
