workflows:
  build_ios_only:
    name: Build iOS Sempre Online
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUILD_NUMBER: 1
    scripts:
      - name: Instalando dependências
        script: flutter pub get

      - name: Build iOS release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - noc@semppreonline.com.br
