name: sempre_online_app
description: "Aplicativo Sempre Online"
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  get: ^4.6.5
  font_awesome_flutter: ^10.2.0

  # speed-test real (Android/iOS)
  speed_test_dart: ^1.0.5+0

  # gráficos
  fl_chart: ^0.71.0

  # Utilitários 
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  http: ^1.2.1
  dio: ^5.0.0
  image_picker: ^1.1.2  
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  url_launcher: ^6.2.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-nova-semppre.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-nova-semppre.png
