// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVSxXi5f74lgB7CQIhvc2RTTGJ-I1Jvgc',
    appId: '1:626864649467:web:399405db0e3d78be5c6c5e',
    messagingSenderId: '626864649467',
    projectId: 'sempre-online-notificacoes',
    authDomain: 'sempre-online-notificacoes.firebaseapp.com',
    storageBucket: 'sempre-online-notificacoes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2cwjHU-iPjLPLbdtaJZOtVHv0mLZWUbA',
    appId: '1:626864649467:android:500773bb58618ebc5c6c5e',
    messagingSenderId: '626864649467',
    projectId: 'sempre-online-notificacoes',
    storageBucket: 'sempre-online-notificacoes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJfL-7Dx5oWIw8l7vTb_x-6YlftESMpaw',
    appId: '1:626864649467:ios:261708e2a726687a5c6c5e',
    messagingSenderId: '626864649467',
    projectId: 'sempre-online-notificacoes',
    storageBucket: 'sempre-online-notificacoes.firebasestorage.app',
    iosBundleId: 'com.example.sempreOnlineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJfL-7Dx5oWIw8l7vTb_x-6YlftESMpaw',
    appId: '1:626864649467:ios:261708e2a726687a5c6c5e',
    messagingSenderId: '626864649467',
    projectId: 'sempre-online-notificacoes',
    storageBucket: 'sempre-online-notificacoes.firebasestorage.app',
    iosBundleId: 'com.example.sempreOnlineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVSxXi5f74lgB7CQIhvc2RTTGJ-I1Jvgc',
    appId: '1:626864649467:web:5e0894b21533b15a5c6c5e',
    messagingSenderId: '626864649467',
    projectId: 'sempre-online-notificacoes',
    authDomain: 'sempre-online-notificacoes.firebaseapp.com',
    storageBucket: 'sempre-online-notificacoes.firebasestorage.app',
  );
}
