platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods',
  :deterministic_uuids => false

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods()
end
